
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CLASS = 2;
  public static final int RPAREN = 13;
  public static final int SEMI = 16;
  public static final int WHILE = 11;
  public static final int TYPEINT = 6;
  public static final int ACCESS = 3;
  public static final int IF = 10;
  public static final int LBRACKET = 4;
  public static final int LPAREN = 12;
  public static final int ID = 14;
  public static final int RBRACKET = 5;
  public static final int BOOLEAN = 19;
  public static final int EOF = 0;
  public static final int TYPEDOUBLE = 7;
  public static final int TYPEBOOLEAN = 8;
  public static final int error = 1;
  public static final int ASSIGN = 15;
  public static final int INTEGER = 18;
  public static final int VOID = 9;
  public static final int DOUBLE = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "ACCESS",
  "LBRACKET",
  "RBRACKET",
  "TYPEINT",
  "TYPEDOUBLE",
  "TYPEBOOLEAN",
  "VOID",
  "IF",
  "WHILE",
  "LPAREN",
  "RPAREN",
  "ID",
  "ASSIGN",
  "SEMI",
  "DOUBLE",
  "INTEGER",
  "BOOLEAN"
  };
}

