
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 16;
  public static final int AND = 21;
  public static final int CLASS = 2;
  public static final int PLUS = 19;
  public static final int OR = 22;
  public static final int RPAREN = 18;
  public static final int EQUAL = 13;
  public static final int SEMI = 26;
  public static final int NOTEQUAL = 14;
  public static final int TYPEINT = 6;
  public static final int NOT = 23;
  public static final int ACCESS = 3;
  public static final int GREATER = 9;
  public static final int LPAREN = 17;
  public static final int LBRACKET = 4;
  public static final int LESSEQUAL = 12;
  public static final int ID = 24;
  public static final int RBRACKET = 5;
  public static final int EOF = 0;
  public static final int DIVIDE = 15;
  public static final int TYPEDOUBLE = 7;
  public static final int MINUS = 20;
  public static final int error = 1;
  public static final int ASSIGN = 25;
  public static final int INTEGER = 28;
  public static final int VOID = 8;
  public static final int GREATEREQUAL = 10;
  public static final int LESS = 11;
  public static final int DOUBLE = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "ACCESS",
  "LBRACKET",
  "RBRACKET",
  "TYPEINT",
  "TYPEDOUBLE",
  "VOID",
  "GREATER",
  "GREATEREQUAL",
  "LESS",
  "LESSEQUAL",
  "EQUAL",
  "NOTEQUAL",
  "DIVIDE",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "PLUS",
  "MINUS",
  "AND",
  "OR",
  "NOT",
  "ID",
  "ASSIGN",
  "SEMI",
  "DOUBLE",
  "INTEGER"
  };
}

