
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EXIT = 20;
  public static final int TIMES = 9;
  public static final int AND = 14;
  public static final int PLUS = 12;
  public static final int OR = 15;
  public static final int RPAREN = 11;
  public static final int EQUAL = 6;
  public static final int SEMI = 19;
  public static final int NOTEQUAL = 7;
  public static final int NOT = 16;
  public static final int GREATER = 2;
  public static final int TRUE = 21;
  public static final int LPAREN = 10;
  public static final int LESSEQUAL = 5;
  public static final int ID = 17;
  public static final int EOF = 0;
  public static final int DIVIDE = 8;
  public static final int FALSE = 22;
  public static final int MINUS = 13;
  public static final int error = 1;
  public static final int ASSIGN = 18;
  public static final int INTEGER = 23;
  public static final int GREATEREQUAL = 3;
  public static final int LESS = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "GREATER",
  "GREATEREQUAL",
  "LESS",
  "LESSEQUAL",
  "EQUAL",
  "NOTEQUAL",
  "DIVIDE",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "PLUS",
  "MINUS",
  "AND",
  "OR",
  "NOT",
  "ID",
  "ASSIGN",
  "SEMI",
  "EXIT",
  "TRUE",
  "FALSE",
  "INTEGER"
  };
}

